// Simplified CRA-style service worker registration for Vite + React
// Registers the service worker generated by Vite PWA plugin (or workbox-build)

export function register() {
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
      navigator.serviceWorker
        .register('/sw.js')
        .catch((err) => console.error('SW registration failed', err));
    });
  }
}
